# prometheus/prometheus.yml
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres-cluster'
    static_configs:
      - targets:
          - 'pg-node-1:5432'
          - 'pg-node-2:5432'
          - 'pg-node-3:5432'
    metrics_path: /probe
    params:
      auth_module: [ pgmon ]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 'pg-exporter:9187'

  - job_name: 'scylla'
    static_configs:
      - targets: ['scylla-node-1:9180', 'scylla-node-2:9180', 'scylla-node-3:9180']